// Copies the pg_txn schema (extension/sql/pg_txn--<v>.sql, the single source)
// into the SDKs, which install it on first use.
import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const dir = path.join(root, "extension/sql");
const file = readdirSync(dir).filter((f) => /^pg_txn--\d+\.\d+\.sql$/.test(f)).sort().at(-1);
const sql = readFileSync(path.join(dir, file), "utf8");
const version = Number(/INSERT INTO txn\.meta VALUES \((\d+)\)/.exec(sql)[1]);
const install = `CREATE SCHEMA txn;\n${sql}`;

writeFileSync(path.join(root, "clients/typescript/client/src/schema.ts"),
  `// Generated by scripts/sync-schema.mjs from extension/sql/${file}. Do not edit.\n` +
  `export const SCHEMA_VERSION = ${version};\n` +
  `export const SCHEMA_SQL = ${JSON.stringify(install)};\n`);
writeFileSync(path.join(root, "clients/elixir/priv/schema.sql"), install);
console.log(`schema v${version} from ${file} -> TypeScript and Elixir clients`);
